version: '3'
services:
  mlchar:
    restart: always
    image: orlopau/mlchar-server:latest
    container_name: mlchar-server
    labels:
      - "traefik.enable=true"
      - "traefik.backend=MLCharServer"
      - "traefik.frontend.rule=Host:mlchar.orlopau.dev"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
    networks:
      - web
networks:
  web:
    external: true