name: Publish Docker image

on:
  push:
    branches: 
      - master
    paths:
      - 'server/*'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build server/ --tag mlchar-server
    - name: Publish Docker
      run: |
        docker login -u orlopau -p ${{ secrets.DOCKER_HUB }}
        docker tag mlchar-server orlopau/mlchar-server:latest
        docker push orlopau/mlchar-server:latest

